### ISSUE TITLE
No contact info!

### ISSUE THREAD

**Issue by rdaland** [colinmorris/crawl-coroner#1]
Dear Colin,
This (crawl-coroner) is a super cool project. You said if someone else was interested in playing with it, to get in contact. I'm interested! Unfortunately I wasn't able to email you directly from github, and there were too many Colin Morrises on google for me to know which was one was you.

Could you provide a way to get your contact info?

Alternatively, you could just email me -- my name is Robert Daland, I should be the first thing to pop up if you Google me.
Thank you!

**Comment by colinmorris** [comment]
Whoops, my bad. I just uploaded a tarball of the data to s3 and put a link in the README. 

If there's anything else I can help with, my e-mail is firstname dot lastname 2 @ gmail.com
